### ISSUE TITLE
Support Community Themes

### ISSUE THREAD

**Issue by phiilu** [packruler/traefik-themepark#26]
I would love to be able to use the community themes that are available from theme-park.dev. For example the Catppuccin theme is available via this URL [https://theme-park.dev/css/community-theme-options/catppuccin-macchiato.css](https://theme-park.dev/css/community-theme-options/catppuccin-macchiato.css). 

> Note: All themes can be listed via [https://theme-park.dev/themes.json](https://theme-park.dev/themes.json)

I tried to get this plugin working with the community theme by using this:

```yaml
plex-catppuccin-macchiato:
  plugin:
    themepark:
      app: community-theme-options
      theme: catppuccin-macchiato
```

But that would result in the following URL: `https://theme-park.dev/css/base/plex/community-theme-options/catppuccin-macchiato.css`

I guess the change required would not be too big to support community themes. I am not really proficient with Go, but I might be able to get something working.

**Comment by packruler** [comment]
I will look into adding support for these themes 👍

**Comment by packruler** [comment]
Sorry for the long delay. However, I have good news this is already supported you just need to tweak your config
```yaml
plex-catppuccin-macchiato:
  plugin:
    themepark:
      app: plex
      theme: catppuccin-macchiato
```
I'm assuming you are trying to theme plex based on the example URL you provided. I have tested and verified this is functional 😁
